title: IFT4055 - Un corpus de métadonnées scientifiques
description: Projet Honor

remote_theme: pages-themes/primer@v0.6.0

plugins:
  - jekyll-include-cache
  
markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: default
